apiVersion: v1
kind: Secret
metadata:
  name: agro-farms-secret
type: Opaque
stringData:
  ConnectionStrings__FarmsDbConnection: "${DB_CONNECTIONSTRING}"
  ElasticApm__SecretToken: "${ELASTIC_APM_SECRET_TOKEN}"
